Hw 2
Pranav-PSU/frontend-homework pull request #2
Opened 2023-04-26 23:43 UTC by Pranav-PSU

01-flexbox: added solutions to the game
02-cssgrid: added solutions to the game
03.count.html: added bootstrap classes and HTML element to match the output with the screenshot
03-count.js: added code to highlight the input word in the text

04-background: added bootstrap classes and HTML elements to match the output with the screenshot
04-background.js: Added the code to change the background color

05-form.html: Created a form using HTML and Bootstrap which is matched with the screenshot.
05-form.js: Added code to get the values and print the output in the console.

External resources used: 
http://jsfiddle.net/5V8mV/1/ : for generating the background colors.
https://getbootstrap.com/docs: for bootstrap classes and components. 

Feedback needed:
I would appreciate any feedback on my implementation, coding standards, and formatting.

2023-04-28 05:35 UTC, Rajashree-Pethkar requested changes
Found some accessibility errors. And the border-radius is missing for form.

<img width="668" alt="Screenshot 2023-04-27 at 10 33 09 PM" src="https://user-images.githubusercontent.com/8189545/235062816-cb39bb38-7d23-4ec6-b33c-2a995736c2e7.png">
<img width="736" alt="Screenshot 2023-04-27 at 10 33 32 PM" src="https://user-images.githubusercontent.com/8189545/235062823-8d81dfe1-d105-41c5-b8b9-c775cec04a57.png">

2023-04-28 23:26 UTC, rohan-singh1 approved these changes
Orphaned form label, but it has already been pointed out by Rajashree. Otherwise looks good.

2023-04-28 23:26 UTC, rohan-singh1 commented on hw2/03-count.html
> +                <label>Highlight all occurences of a word:</label>
for attribute missing

2023-04-30 20:26 UTC, Pranav-PSU commented on hw2/03-count.html
> +                <label>Highlight all occurences of a word:</label>
fixed

2023-04-30 20:28 UTC, merged

2023-04-30 20:28 UTC, Pranav-PSU commented
All suggested changes are done. Merging the pull request.